export const DISPUTE_ESCROW_ABI = [
  "function version() pure returns (string)",
  "function disputeCount() view returns (uint256)",
  "function createDispute(address defendant,string description) payable returns (uint256)",
  "function joinDispute(uint256 id) payable",
  "function submitEvidence(uint256 id,string evidenceUrl)",
  "function requestArbitration(uint256 id) payable returns (uint256)",
  "function retryFailedStage(uint256 id) payable returns (uint256)",
  "function recoverFailedDispute(uint256 id)",
  "function markCurrentStageTimedOut(uint256 id)",
  "function claimExpiry(uint256 id)",
  "function withdraw()",
  "function minimumAgentBudget() view returns (uint256)",
  "function requiredBudget(uint8 stage) view returns (uint256)",
  "function stageRequestedAt(uint256 id) view returns (uint256)",
  "function withdrawable(address account) view returns (uint256)",
  "function getPartyCaseIds(address party) view returns (uint256[])",
  "function getStageRequestIds(uint256 id) view returns (uint256[5])",
  "function getDispute(uint256 id) view returns (tuple(address plaintiff,address defendant,address arbitrationFunder,uint256 plaintiffDeposit,uint256 defendantDeposit,uint256 agentBudget,uint256 createdAt,uint256 failedAt,uint8 state,uint8 currentStage,uint8 failedStage,address winner,uint8 confidence,string description,string plaintiffEvidenceUrl,string defendantEvidenceUrl,string plaintiffSummary,string defendantSummary,string validationSummary,string skepticSummary,string verdictReasoning))",
  "event DisputeCreated(uint256 indexed id,address indexed plaintiff,address indexed defendant,uint256 amount)",
  "event DisputeJoined(uint256 indexed id,address indexed defendant,uint256 amount)",
  "event EvidenceSubmitted(uint256 indexed id,address indexed by,string url)",
  "event ArbitrationStarted(uint256 indexed id,address indexed funder,uint256 budget)",
  "event AgentRequestCreated(uint256 indexed id,uint256 indexed requestId,uint8 stage,uint256 budget)",
  "event AgentStepCompleted(uint256 indexed id,uint256 indexed requestId,uint8 stage,string output)",
  "event AgentRequestFailed(uint256 indexed id,uint256 indexed requestId,uint8 stage,uint8 status,string reason)",
  "event AgentStageRetried(uint256 indexed id,uint8 stage,address indexed funder,uint256 addedBudget)",
  "event VerdictDelivered(uint256 indexed id,address indexed winner,uint8 confidence,string reasoning)",
  "event FundsCredited(uint256 indexed id,address indexed account,uint256 amount,string reason)",
  "event Withdrawal(address indexed account,uint256 amount)"
];
